#!/bin/bash
set -eux

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
# TODO: Is this still needed?
#pushd $HOME

OSTYPE=$(uname -s)
case $OSTYPE in
  Darwin)
    BOOTSTRAP_OS=osx
    ;;
  *)
    BOOTSTRAP_OS=linux
    ;;
esac

BOOTSTRAP_DIR=${BOOTSTRAP_DIR:-"${HOME}/.bootstrap.d"}

yadm submodule update --recursive --init

for SOURCE in ${BOOTSTRAP_DIR}/*.sh; do
  #env bash -c "set -eux; source ${SOURCE}"
  source ${SOURCE}
done
