#!/bin/bash

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
pushd $HOME
echo "Init submodules"
yadm submodule update --recursive --init

source $HOME/.yadm/bootstrap-pre.sh
if [[ $(uname -s) = "Darwin" ]]; then
  source $HOME/.yadm/bootstrap-osx.sh
elif [[ $(uname -s) = "Linux" ]]; then
  source $HOME/.yadm/bootstrap-linux.sh
else
  echo "Unknown system"
fi
source $HOME/.yadm/bootstrap-post.sh
